### ISSUE TITLE
Error when launching vim 

### ISSUE THREAD

**Issue by amineden** [WolfgangMehner/c-support#2]
whenever I run vim I get the following error    
` Error detected while processing /home/amine/.vim/plugin/c.vim[2965]..function mmtoolbox#tools#Load[43]..<SNR>29_LoadTool[10]..script /home/amine/.vim/autoload/mmtoolbox/doxygen.vim:
line  277: E1208: -complete used without allowing argumentsline  278: E1208: -complete used without allowing argumentsline  279: E1208: -complete used without allowing argumentsPress ENTER or type command to continue`

**Comment by WolfgangMehner** [comment]
Thanks for reporting this issue. This is a check and associated error (E1208) which was introduced by a recent version of Vim.

**Comment by amineden** [comment]
> Thanks for reporting this issue. This is a check and associated error (E1208) which was introduced by a recent version of Vim.

thank you for fixing it
